### ISSUE TITLE
Getting Z-wave stick to work with WSL on Ubuntu?

### ISSUE THREAD

**Issue by kspearrin** [sameer/python-openzwave-sniffer#1]
Hi,
Thanks for this library and instructions.

I am trying to get it to work on Windows 10 with WSL on Ubuntu. I noticed that your README has instructions for WSL. Have you got it working there before? I have the [Aeotec Z-wave Stick](https://aeotec.com/z-wave-usb-stick/) and have it plugged into COM4 on the machine as shown by Device Manager.

![image](https://user-images.githubusercontent.com/1190944/60691382-3b181980-9e9d-11e9-8a3e-98fbf1c43df8.png)

I have configured `/dev/ttyS4` as covered in the following article: https://www.scivision.dev/usb-tty-windows-subsystem-for-linux/

```
chmod 666 /dev/ttyS4
stty -F /dev/ttyS4 115200
```

When I try to run the sniffer, I just get the following:

```
$ ./run.sh /dev/ttyS4
2019-07-04 17:43:26,235 INFO openzwave/main.py[13328] -- Launching with ZWave Stick at /dev/ttyS4
2019-07-04 17:43:26,259 INFO openzwave/main.py[13328] -- Starting network...
2019-07-04 17:43:26,260 INFO openzwave [13328] -- Start Openzwave network.
2019-07-04 17:43:26,511 INFO openzwave/main.py[13328] -- Stopped
```

Any ideas?

**Comment by sameer** [comment]
Hi @kspearrin,

I'm just glad this guide came in handy for others. From what I remember, chmodding it should work out of the box. Couple of things to check on:
* Have you tried running the WSL shell as admin?
* Is it showing up as ttyACM4 instead?
* Does your build of windows support COM ports to tty on WSL? Could test with Arduino or another device for that

**Comment by kspearrin** [comment]
1. I just tried running shell as admin, it did not seem to change anything.

2. ttyACM4 doesn't seem to exist in WSL.

```
$ ./run.sh /dev/ttyACM4
2019-07-04 18:05:16,386 INFO openzwave/main.py[13371] -- Launching with ZWave Stick at /dev/ttyACM4
2019-07-04 18:05:16,408 ERROR openzwave/main.py[13371] -- Unable to create ZWave Network: Error when retrieving device /dev/ttyACM4 : ['Traceback (most recent call last):\n', '  File "/home/kyle/project/python-openzwave-sniffer/venv/lib/python3.6/site-packages/openzwave/option.py", line 110, in __init__\n    raise ZWaveException(u"Can\'t find device %s : %s" % (device, traceback.format_exception(*sys.exc_info())))\n', 'openzwave.object.ZWaveException: "Zwave Generic Exception : Can\'t find device /dev/ttyACM4 : [\'NoneType: None\\\\n\']"\n']
```

```
$ cd /dev
$ ls
block   tty2     ttyS110  ttyS124  ttyS138  ttyS151  ttyS165  ttyS179  ttyS2   ttyS33  ttyS47  ttyS60  ttyS74  ttyS88
fd      ttyS0    ttyS111  ttyS125  ttyS139  ttyS152  ttyS166  ttyS18   ttyS20  ttyS34  ttyS48  ttyS61  ttyS75  ttyS89
kmsg    ttyS1    ttyS112  ttyS126  ttyS14   ttyS153  ttyS167  ttyS180  ttyS21  ttyS35  ttyS49  ttyS62  ttyS76  ttyS9
lxss    ttyS10   ttyS113  ttyS127  ttyS140  ttyS154  ttyS168  ttyS181  ttyS22  ttyS36  ttyS5   ttyS63  ttyS77  ttyS90
null    ttyS100  ttyS114  ttyS128  ttyS141  ttyS155  ttyS169  ttyS182  ttyS23  ttyS37  ttyS50  ttyS64  ttyS78  ttyS91
ptmx    ttyS101  ttyS115  ttyS129  ttyS142  ttyS156  ttyS17   ttyS183  ttyS24  ttyS38  ttyS51  ttyS65  ttyS79  ttyS92
pts     ttyS102  ttyS116  ttyS13   ttyS143  ttyS157  ttyS170  ttyS184  ttyS25  ttyS39  ttyS52  ttyS66  ttyS8   ttyS93
random  ttyS103  ttyS117  ttyS130  ttyS144  ttyS158  ttyS171  ttyS185  ttyS26  ttyS4   ttyS53  ttyS67  ttyS80  ttyS94
shm     ttyS104  ttyS118  ttyS131  ttyS145  ttyS159  ttyS172  ttyS186  ttyS27  ttyS40  ttyS54  ttyS68  ttyS81  ttyS95
stderr  ttyS105  ttyS119  ttyS132  ttyS146  ttyS16   ttyS173  ttyS187  ttyS28  ttyS41  ttyS55  ttyS69  ttyS82  ttyS96
stdin   ttyS106  ttyS12   ttyS133  ttyS147  ttyS160  ttyS174  ttyS188  ttyS29  ttyS42  ttyS56  ttyS7   ttyS83  ttyS97
stdout  ttyS107  ttyS120  ttyS134  ttyS148  ttyS161  ttyS175  ttyS189  ttyS3   ttyS43  ttyS57  ttyS70  ttyS84  ttyS98
tty     ttyS108  ttyS121  ttyS135  ttyS149  ttyS162  ttyS176  ttyS19   ttyS30  ttyS44  ttyS58  ttyS71  ttyS85  ttyS99
tty0    ttyS109  ttyS122  ttyS136  ttyS15   ttyS163  ttyS177  ttyS190  ttyS31  ttyS45  ttyS59  ttyS72  ttyS86  urandom
tty1    ttyS11   ttyS123  ttyS137  ttyS150  ttyS164  ttyS178  ttyS191  ttyS32  ttyS46  ttyS6   ttyS73  ttyS87  zero
```

3. I am using the latest Windows 10 build (1903, spring 2019). I assume it supports COM ports to TTY on WSL, as it is much newer than these articles stating that it does work. I am not sure how I can test it with another device. I don't have an Arduino.

- Were you able to get this working with WSL in the past?
- What Z-wave stick were you using?

**Comment by sameer** [comment]
> Were you able to get this working with WSL in the past?

Yes, I wrote a couple quick scripts so other people at my university could use it.

> What Z-wave stick were you using?

The same brand but not sure about the generation. It looks exactly the same as the one you linked.

**Comment by kspearrin** [comment]
So I played around with it a bit more and moved the z-wave stick to another USB port and now it seems to work. Not sure what is up with that other port, but COM5 and COM6 are both working great.

Also worth noting, I didn't even need to `chmod 666` or `stty -F` the tty ports. It seems to be plug and play if your user is in the `dialout` group.

Thanks again!

**Comment by sameer** [comment]
Great, have fun!

-------- Original-Nachricht --------
An 4. Juli 2019, 20:35, Kyle Spearrin schrieb:
